services:
  hub:
    image: nginx:alpine
    container_name: portfolio
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      # On retire le PathPrefix pour ne garder que le Host
      - "traefik.http.routers.hub.rule=Host(`lab.zanza-creation.com`)"
      - "traefik.http.routers.hub.entrypoints=websecure"
      - "traefik.http.routers.hub.tls.certresolver=myresolver"

networks:
  traefik:
    external: true



# services:
#   hub:
#     image: nginx:alpine
#     container_name: portfolio-hub
#     restart: always
#     volumes:
#       - ./html:/usr/share/nginx/html:ro
#       # - ./img:/usr/share/nginx/html/img:ro
#     networks:
#       - web
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.hub.rule=Host(`lab.zanza-creation.com`) && PathPrefix(`/`)"
#       - "traefik.http.routers.hub.entrypoints=websecure"
#       - "traefik.http.routers.hub.tls.certresolver=myresolver"

# networks:
#   web:
#     external: true